#!/bin/bash
echo "Packaging and publishing $kd_build_type build of $kd_project version $kd_package_name"
# For now, relying on a preexisting build.
# bash ./do/generatemetadata
# dotnet build $kd_module/$kd_module.csproj
# dotnet build $kd_module.Specifications/$kd_module.Specifications.csproj
cat -v ./do/generatemetadata
./do/generatemetadata
ls -l | cat -v
cd $kd_module
dotnet pack $kd_module.csproj --no-build --output .. --verbosity normal
cd ../$kd_module.Specifications
dotnet pack $kd_module.Specifications.csproj --no-build --output .. --verbosity normal
cd ..
ls
# dotnet nuget push --api-key $kd_package_repo_api_key
