#!/bin/bash
echo "Packaging and publishing $kd_build_type build of $kd_project version $kd_package_name"
echo "The super secret key is $super_secret_key"
echo "Spec package name is $kd_spec_package_name"
# For now, relying on a preexisting build.
dotnet pack $kd_module/$kd_module.csproj --no-build --output .. --verbosity normal
dotnet nuget push $kd_package_name.nupkg --api-key $kd_package_repo_api_key --source https://api.nuget.org/v3/index.json --no-service-endpoint
dotnet pack $kd_module.Specifications/$kd_module.Specifications.csproj --no-build --output .. --verbosity normal
dotnet nuget push $kd_spec_package_name.nupkg --api-key $kd_package_repo_api_key --source https://api.nuget.org/v3/index.json --no-service-endpoint
